### ISSUE TITLE
Fails with perls < 5.10

### ISSUE THREAD

**Issue by andk** [mlawren/p5-OptArgs2#2]
As per subject. Best illustrated with the matrix: 

http://matrix.cpantesters.org/?dist=OptArgs2%200.0.6

Sample fail report:

http://www.cpantesters.org/cpan/report/474f7fee-4131-11e6-aba3-54095cc2a771

Apparently the // operator is to blame. 

It would be cool if you could declare your requirement. That way the FAILS are converted to UNKNOWNS. Details about how to do it are on this page: http://wiki.cpantesters.org/wiki/CPANAuthorNotes

HTH&&Thanks,

**Comment by mlawren** [comment]
Thanks for the report. This should be fixed by commit 0238819 and will appear in a new releasse soonish.
